# Standards: 1.2
---
- name: Create mixin directory
  file:
    path: /etc/systemd/resolved.conf.d
    state: directory
  tags:
    - resolved

- name: Link resolver config
  when: resolved_stub_listener
  notify:
    - Restart resolved
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    force: True
    state: link
  tags:
    - resolved

- name: Write resolver config
  when: not resolved_stub_listener
  notify:
    - Restart resolved
  template:
    src: resolv.j2
    dest: /etc/resolv.conf
    force: True
  tags:
    - resolved

- name: Mask dhcp config
  notify:
    - Restart resolved
  when: resolved_dhcp_mask
  file:
    src: /dev/null
    dest: "/etc/systemd/resolved.conf.d/{{ resolved_dhcp_name }}"
    force: True
    state: link
  tags:
    - resolved

- name: Unmask dhcp config
  notify:
    - Restart resolved
  when: not resolved_dhcp_mask
  file:
    path: "/etc/systemd/resolved.conf.d/{{ resolved_dhcp_name }}"
    state: absent
  tags:
    - resolved

- name: Write systemd config
  notify:
    - Restart resolved
  template:
    src: config.j2
    dest: /etc/systemd/resolved.conf
  tags:
    - resolved

- name: Start resolved service
  systemd:
    name: systemd-resolved
    state: started
    daemon_reload: True
    masked: False
    enabled: True
  tags:
    - resolved

...
